import * as Dialog from '@radix-ui/react-dialog'
import { useQuery } from '@tanstack/react-query'
import { Bell, CalendarClock, CalendarDays, ChevronLeft, CircleStar, FlaskConical, GraduationCap, House, List, Menu, Moon, PanelLeftClose, PanelLeftOpen, Settings, ShieldCheck, Sun, Trophy, Waypoints, X } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { getCrawlerStatus } from '../../api/crawler'
import { useTheme } from '../../stores/theme'
import { cn } from '../../utils/cn'
import { relativeTime } from '../../utils/format'
import { CrawlerButton } from './CrawlerButton'
import { SearchDialog } from '../search/SearchDialog'

const groups=[
  {label:'总览',items:[{to:'/',label:'首页',icon:House},{to:'/today',label:'今日',icon:CalendarDays},{to:'/deadlines',label:'即将截止',icon:CalendarClock}]},
  {label:'分类',items:[{to:'/competitions',label:'全部竞赛',icon:Trophy},{to:'/competitions/algorithm',label:'算法竞赛',icon:Waypoints},{to:'/cybersecurity',label:'网络安全',icon:ShieldCheck},{to:'/training',label:'实训 / 实习',icon:GraduationCap},{to:'/research',label:'科研 / 实验室',icon:FlaskConical},{to:'/postgraduate',label:'推免',icon:GraduationCap}]},
  {label:'管理',items:[{to:'/favorites',label:'收藏',icon:CircleStar},{to:'/notices',label:'全部通知',icon:List},{to:'/sources',label:'数据源',icon:Bell},{to:'/settings',label:'设置',icon:Settings}]},
]
const mobile=[{to:'/',label:'首页',icon:House},{to:'/today',label:'今日',icon:CalendarDays},{to:'/deadlines',label:'截止',icon:CalendarClock},{to:'/favorites',label:'收藏',icon:CircleStar}]

function NavItems({collapsed=false,onSelect}:{collapsed?:boolean;onSelect?:()=>void}){return <nav className="space-y-5">{groups.map(group=><div key={group.label}>{!collapsed&&<div className="mb-1 px-3 text-[11px] font-semibold tracking-wider text-zinc-400">{group.label}</div>}<div className="space-y-0.5">{group.items.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={onSelect} title={collapsed?label:undefined} className={({isActive})=>cn('flex h-9 items-center rounded-lg text-sm transition-colors',collapsed?'justify-center px-2':'gap-3 px-3',isActive?'bg-indigo-50 font-medium text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300':'text-zinc-600 hover:bg-zinc-100 hover:text-zinc-950 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-zinc-100')}><Icon className="h-4 w-4 shrink-0"/>{!collapsed&&label}</NavLink>)}</div></div>)}</nav>}

export function AppShell(){const [collapsed,setCollapsed]=useState(()=>localStorage.getItem('jlu-sidebar')==='collapsed');const [drawer,setDrawer]=useState(false);const {theme,setTheme}=useTheme();const crawler=useQuery({queryKey:['crawler'],queryFn:getCrawlerStatus,refetchInterval:60_000});const toggle=()=>{const next=!collapsed;setCollapsed(next);localStorage.setItem('jlu-sidebar',next?'collapsed':'expanded')};const width=collapsed?'md:pl-[72px]':'md:pl-[232px]';return <div className="min-h-screen bg-zinc-50 text-zinc-900 transition-colors dark:bg-zinc-950 dark:text-zinc-100">
  <aside className={cn('fixed inset-y-0 left-0 z-30 hidden border-r border-zinc-200 bg-white px-3 py-4 transition-[width] dark:border-zinc-800 dark:bg-zinc-900 md:flex md:flex-col',collapsed?'w-[72px]':'w-[232px]')}><div className={cn('mb-5 flex h-10 items-center',collapsed?'justify-center':'gap-3 px-2')}><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white"><Bell className="h-5 w-5"/></div>{!collapsed&&<div className="min-w-0"><div className="truncate font-semibold tracking-tight">吉大通知助手</div><div className="text-xs text-zinc-400">个人通知情报中心</div></div>}</div><div className="min-h-0 flex-1 overflow-y-auto"><NavItems collapsed={collapsed}/></div><div className="mt-3 border-t border-zinc-100 pt-3 dark:border-zinc-800">{!collapsed&&<div className="mb-2 rounded-lg bg-zinc-50 p-3 text-xs dark:bg-zinc-800/60"><div className="flex items-center gap-2 font-medium"><span className={cn('h-2 w-2 rounded-full',crawler.isError?'bg-rose-500':'bg-emerald-500')}/>{crawler.isError?'后端离线':'后端在线'}</div><div className="mt-1.5 text-zinc-400">上次同步 {relativeTime(crawler.data?.last_run)}</div></div>}<button onClick={toggle} className={cn('flex h-9 w-full items-center rounded-lg text-xs text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800',collapsed?'justify-center':'gap-2 px-3')} aria-label={collapsed?'展开侧边栏':'折叠侧边栏'}>{collapsed?<PanelLeftOpen className="h-4 w-4"/>:<><PanelLeftClose className="h-4 w-4"/>折叠侧边栏</>}</button></div></aside>
  <div className={cn('transition-[padding]',width)}><header className="sticky top-0 z-20 flex h-16 items-center gap-2 border-b border-zinc-200 bg-white/90 px-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/90 sm:gap-3 sm:px-6 lg:px-8"><button className="grid h-9 w-9 place-items-center rounded-lg text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800 md:hidden" onClick={()=>setDrawer(true)} aria-label="打开菜单"><Menu className="h-5 w-5"/></button><SearchDialog/><CrawlerButton/><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="grid h-9 w-9 place-items-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800" aria-label={theme==='dark'?'切换浅色主题':'切换深色主题'}>{theme==='dark'?<Sun className="h-4 w-4"/>:<Moon className="h-4 w-4"/>}</button></header><main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><Outlet/></main></div>
  <nav className="fixed inset-x-0 bottom-0 z-40 flex h-[68px] items-center justify-around border-t border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900 md:hidden">{mobile.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>cn('flex min-w-14 flex-col items-center gap-1 text-[11px]',isActive?'font-medium text-indigo-600 dark:text-indigo-300':'text-zinc-500')}><Icon className="h-5 w-5"/>{label}</NavLink>)}<button onClick={()=>setDrawer(true)} className="flex min-w-14 flex-col items-center gap-1 text-[11px] text-zinc-500"><Menu className="h-5 w-5"/>更多</button></nav>
  <Dialog.Root open={drawer} onOpenChange={setDrawer}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-zinc-950/40"/><Dialog.Content aria-describedby={undefined} className="fixed inset-y-0 right-0 z-50 w-[min(86vw,340px)] overflow-y-auto border-l border-zinc-200 bg-white p-4 shadow-2xl dark:border-zinc-700 dark:bg-zinc-900"><Dialog.Title className="flex items-center justify-between font-semibold">全部功能<Dialog.Close className="grid h-9 w-9 place-items-center rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800" aria-label="关闭菜单"><X className="h-5 w-5"/></Dialog.Close></Dialog.Title><div className="mt-5"><NavItems onSelect={()=>setDrawer(false)}/></div><button onClick={()=>setDrawer(false)} className="mt-6 inline-flex items-center gap-2 text-xs text-zinc-400"><ChevronLeft className="h-3 w-3"/>返回当前页面</button></Dialog.Content></Dialog.Portal></Dialog.Root>
</div>}
