import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, CalendarClock, ExternalLink, FileText, Star, Users } from 'lucide-react'
import { useEffect, useRef } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getNotice, setNoticeFavorite, setNoticeRead } from '../api/notices'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { ErrorState, PageSkeleton } from '../components/ui/Feedback'
import { useToast } from '../stores/toast'
import { cn } from '../utils/cn'
import { fullDate } from '../utils/format'
import { categoryLabels } from '../utils/labels'

export function NoticeDetailPage(){const id=Number(useParams().id);const client=useQueryClient();const toast=useToast();const marked=useRef(false);const q=useQuery({queryKey:['notice',id],queryFn:()=>getNotice(id),enabled:Number.isFinite(id)});const fav=useMutation({mutationFn:(value:boolean)=>setNoticeFavorite(id,value),onSuccess:()=>{client.invalidateQueries({queryKey:['notice',id]});client.invalidateQueries({queryKey:['notices']});toast(q.data?.is_favorite?'已取消收藏':'收藏成功')},onError:()=>toast('收藏操作失败','error')});useEffect(()=>{if(q.data&&!q.data.is_read&&!marked.current){marked.current=true;setNoticeRead(id,true).then(()=>{client.invalidateQueries({queryKey:['notices']});client.invalidateQueries({queryKey:['dashboard']})}).catch(()=>undefined)}},[q.data,id,client]);if(q.isPending)return <PageSkeleton/>;if(q.isError)return <ErrorState message={q.error.message} retry={()=>q.refetch()}/>;const n=q.data;return <div className="mx-auto max-w-5xl"><Link to="/notices" className="mb-5 inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"><ArrowLeft className="h-4 w-4"/>返回通知列表</Link><article><div className="flex flex-wrap items-center gap-2"><Badge className="border-transparent bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{categoryLabels[n.category??'']??'其他'}</Badge>{n.status==='updated'&&<Badge>已更新</Badge>}</div><div className="mt-4 flex items-start gap-4"><h1 className="min-w-0 flex-1 text-2xl font-bold leading-[1.4] tracking-tight sm:text-3xl">{n.title}</h1><Button size="icon" onClick={()=>fav.mutate(!n.is_favorite)} disabled={fav.isPending} aria-label={n.is_favorite?'取消收藏':'收藏通知'}><Star className={cn('h-4 w-4',n.is_favorite&&'fill-amber-400 text-amber-500')}/></Button></div><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-zinc-500"><span>{n.publisher??n.sources[0]?.name??'发布部门待定'} · {fullDate(n.publish_date)}</span><span>优先级 {n.importance_score}</span><a href={n.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-indigo-600 hover:underline">查看原网页<ExternalLink className="h-3.5 w-3.5"/></a></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-5"><Card className="p-5"><h2 className="font-semibold">摘要</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Summary title="这是什么" text="暂无结构化摘要"/><Summary title="适合谁" text={n.target_students??'通知中未说明'}/><Summary title="建议" text="暂无结构化建议"/></div></Card><Card className="p-5"><h2 className="font-semibold">原通知内容</h2>{n.content?<div className="mt-5 max-w-3xl space-y-4 text-[15px] leading-8 text-zinc-700 dark:text-zinc-300">{n.content.split(/\n+/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div>:<p className="mt-4 text-sm text-zinc-500">尚未抓取到正文，请查看原网页。</p>}</Card>{n.attachments.length>0&&<Card className="p-5"><h2 className="font-semibold">附件</h2><div className="mt-3 space-y-2">{n.attachments.map((a,index)=><a key={`${a.url}-${index}`} href={a.url} target="_blank" rel="noreferrer" className="flex min-w-0 items-center gap-3 rounded-lg border border-zinc-200 p-3 text-sm hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"><FileText className="h-4 w-4 shrink-0 text-indigo-500"/><span className="truncate">{a.name??a.title??'附件'}</span><ExternalLink className="ml-auto h-3.5 w-3.5 shrink-0 text-zinc-400"/></a>)}</div></Card>}</div>
        <aside className="space-y-5"><Card className="p-5"><h2 className="font-semibold">关键信息</h2><dl className="mt-4 space-y-4"><Key icon={<CalendarClock/>} label="报名截止" value={fullDate(n.registration_deadline)}/><Key label="距离截止" value={n.days_until_deadline===null?'通知中未说明':n.days_until_deadline<0?'已截止':`${n.days_until_deadline} 天`}/><Key label="比赛时间" value={fullDate(n.event_start)}/><Key label="报名方式" value={n.registration_method??'通知中未说明'}/><Key icon={<Users/>} label="面向对象" value={n.target_students??'通知中未说明'}/><Key label="竞赛级别" value={n.competition_level??'通知中未说明'}/></dl></Card><Card className="p-5"><h2 className="font-semibold">下一步</h2><p className="mt-3 text-sm leading-6 text-zinc-500">当前未提取到明确行动项。</p></Card><Card className="p-5"><h2 className="font-semibold">来源</h2><div className="mt-3 flex flex-wrap gap-2">{n.sources.map(s=><a key={s.code} href={s.url??n.url} target="_blank" rel="noreferrer"><Badge className="hover:border-indigo-300 hover:text-indigo-600">{s.name}</Badge></a>)}</div></Card></aside></div></article></div>}
function Summary({title,text}:{title:string;text:string}){return <div><div className="text-xs font-medium text-zinc-400">{title}</div><p className="mt-1.5 text-sm leading-6 text-zinc-600 dark:text-zinc-300">{text}</p></div>}
function Key({icon,label,value}:{icon?:React.ReactNode;label:string;value:string}){return <div className="flex items-start gap-2.5">{icon&&<span className="mt-0.5 [&>svg]:h-4 [&>svg]:w-4 text-zinc-400">{icon}</span>}<div className={icon?'':'pl-6'}><dt className="text-xs text-zinc-400">{label}</dt><dd className="mt-0.5 text-sm font-medium">{value}</dd></div></div>}
