import { useQuery } from '@tanstack/react-query'
import { CheckCircle2, CircleOff, Clock3, ExternalLink, TriangleAlert } from 'lucide-react'
import { getSources } from '../api/sources'
import { PageHeader } from '../components/layout/PageHeader'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { ErrorState, PageSkeleton } from '../components/ui/Feedback'
import { relativeTime } from '../utils/format'
import { sourceStatusLabels } from '../utils/labels'

export function SourcesPage(){const sources=useQuery({queryKey:['sources'],queryFn:getSources});if(sources.isPending)return <PageSkeleton/>;if(sources.isError)return <ErrorState message={sources.error.message} retry={()=>sources.refetch()}/>;return <><PageHeader title="数据源" description="查看各通知来源的运行状态与最近同步情况。"/><div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{sources.data.map(source=>{const healthy=source.status==='healthy';const disabled=source.status==='disabled'||source.status==='unconfigured';const Icon=healthy?CheckCircle2:disabled?CircleOff:TriangleAlert;return <Card key={source.code} className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold">{source.name}</h2><a href={source.base_url} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-xs text-zinc-400 hover:text-indigo-600">访问网站<ExternalLink className="h-3 w-3"/></a></div><Badge className={healthy?'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300':disabled?'border-zinc-200 bg-zinc-100 text-zinc-600 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300':'border-amber-200 bg-amber-50 text-amber-700'}><Icon className="mr-1 h-3 w-3"/>{sourceStatusLabels[source.status]??source.status}</Badge></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-zinc-100 pt-4 text-xs dark:border-zinc-800"><div><div className="text-zinc-400">最近检查</div><div className="mt-1 font-medium">{relativeTime(source.last_checked_at)}</div></div><div><div className="text-zinc-400">最近成功</div><div className="mt-1 font-medium">{relativeTime(source.last_success_at)}</div></div><div><div className="text-zinc-400">发现通知</div><div className="mt-1 font-medium tabular-nums">{source.notice_count}</div></div></div>{source.code==='oa'&&<div className="mt-4 rounded-lg bg-zinc-50 p-3 text-xs leading-5 text-zinc-500 dark:bg-zinc-800/60">{source.message??'当前未完成首次登录配置。'}<br/>回到可正常访问 OA 的网络环境后，可执行登录初始化命令继续设置。</div>}{source.last_error&&<div className="mt-4 flex gap-2 rounded-lg bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950 dark:text-amber-300"><Clock3 className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{source.last_error}</div>}</Card>})}</div></>}
