import * as Dialog from '@radix-ui/react-dialog'
import { useQuery } from '@tanstack/react-query'
import { Search, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { searchNotices } from '../../api/notices'
import { categoryLabels } from '../../utils/labels'
import { shortDate } from '../../utils/format'
import { useDebouncedValue } from '../../hooks/useDebouncedValue'

export function SearchDialog() {
  const [open,setOpen]=useState(false);const [keyword,setKeyword]=useState('');const navigate=useNavigate();const debouncedKeyword=useDebouncedValue(keyword.trim())
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[])
  const q=useQuery({queryKey:['search',debouncedKeyword],queryFn:()=>searchNotices(debouncedKeyword),enabled:debouncedKeyword.length>0})
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="flex h-9 min-w-0 flex-1 items-center gap-2 rounded-lg border border-zinc-200 bg-zinc-50 px-3 text-left text-sm text-zinc-400 dark:border-zinc-700 dark:bg-zinc-900 sm:max-w-md"><Search className="h-4 w-4"/><span className="truncate">搜索通知、学院或关键词</span><kbd className="ml-auto hidden rounded border bg-white px-1.5 py-0.5 text-[10px] text-zinc-500 dark:bg-zinc-800 sm:block">Ctrl K</kbd></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-zinc-950/40 backdrop-blur-[2px]"/><Dialog.Content aria-describedby={undefined} className="fixed left-1/2 top-[12vh] z-50 w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-2xl dark:border-zinc-700 dark:bg-zinc-900"><Dialog.Title className="sr-only">搜索通知</Dialog.Title><div className="flex items-center gap-3 border-b border-zinc-200 px-4 dark:border-zinc-800"><Search className="h-5 w-5 text-zinc-400"/><input autoFocus value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="输入蓝桥杯、CTF、推免、实验室……" className="h-14 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-zinc-400"/><Dialog.Close className="grid h-8 w-8 place-items-center rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800" aria-label="关闭搜索"><X className="h-4 w-4"/></Dialog.Close></div><div className="max-h-[60vh] min-h-48 overflow-y-auto p-2">{!keyword?<div className="grid h-44 place-items-center text-sm text-zinc-400">输入关键词开始搜索</div>:q.isPending?<div className="grid h-44 place-items-center text-sm text-zinc-400">正在搜索……</div>:q.data?.items.length?q.data.items.map(n=><button key={n.id} onClick={()=>{setOpen(false);navigate(`/notices/${n.id}`)}} className="flex w-full items-start gap-3 rounded-xl p-3 text-left hover:bg-zinc-50 dark:hover:bg-zinc-800"><span className="mt-2 h-2 w-2 rounded-full bg-indigo-500"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{n.title}</span><span className="mt-1 block text-xs text-zinc-500">{categoryLabels[n.category??'']??'其他'} · {n.sources[0]?.name??'来源待定'} · {shortDate(n.publish_date)}</span></span></button>):<div className="grid h-44 place-items-center text-sm text-zinc-400">没有找到相关通知</div>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
